spring:
  application:
    name: MiniBankingApp
  
  # PostgreSQL Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/minibanking
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  
  # JPA/Hibernate Configuration
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: minibanking_schema

# JWT Configuration
jwt:
  secret: mySecretKeyForJWTTokenGenerationAndValidation1234567890abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789
  expiration: PT24H # 24 hours
  refresh:
    expiration: P7D # 7 days

# Logging Configuration
logging:
  level:
    web: DEBUG
    org.springframework.web: DEBUG
    com.mini.MiniBankingApp: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Swagger Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  show-actuator: true